resources:
  gpu: true

data:
  data_name: EuroSAT
  n: 160
  n_public: 20
  n_test: 10
  n_valid: 10

models:
  architecture: ResNet18
  lr: 0.001
  student_epochs: 20
  teacher_epochs: 5
  weight_decay: 5.0e-05

pate:
  aggregators: [confident]
  budgets:
    wGNMax: # regular
      - [5., 9., 15.0]

  deltas: [1.0e-05]
  distributions:
    - 0: [0.54, 0.37, 0.09]
      1: [0.54, 0.37, 0.09]
      2: [0.54, 0.37, 0.09]
      3: [0.54, 0.37, 0.09]
      4: [0.54, 0.37, 0.09]
      5: [0.54, 0.37, 0.09]
      6: [0.54, 0.37, 0.09]
      7: [0.54, 0.37, 0.09]
      8: [0.54, 0.37, 0.09]
      9: [0.54, 0.37, 0.09]
  limits: [budgets]
  n_labels: 2000
  nums_teachers: [11]
  precision: 0.01
  seeds: [9]
  seeds2: [0, 1, 2]
  sigmas: [4]
  sigmas1: [15]
  ts: [20]